export const bodyData = [
  {
    path: "aerosmith",
    artistName: "Aerosmith",
    musics: [
      "Aerosmith - Crazy.mp3",
      "Aerosmith - Cryin'.mp3",
      "Aerosmith - I Don't Want to Miss a Thing.mp3",
    ],
    artistID: 0,
  },
  {
    path: "air-supply",
    artistName: "Air Supply",
    musics: [
      "Air Supply - Chances.mp3",
      "Air Supply - Having You Near Me.mp3",
      "Air Supply - I Can Wait Forever.mp3",
      "Air Supply - I Can't Let Go.mp3",
      "Air Supply - I'll Never Get Enough of You.mp3",
      "Air Supply - Lonely Is The Night.mp3",
      "Air Supply - Making Love Out of Nothing at All.mp3",
      "Air Supply - Sweet Dreams.mp3",
    ],
    artistID: 1,
  },
  {
    path: "akon",
    artistName: "Akon",
    musics: [
      "Akon - Beautiful.mp3",
      "Akon - Benjamin.mp3",
      "Akon - Good Girls Lie.mp3",
      "Akon - I Can't Wait.mp3",
      "Akon - I Wanna Love You.mp3",
      "Akon - Keep you much longer.mp3",
      "Akon - Lonely.mp3",
      "Akon - Pot Of Gold.mp3",
      "Akon - Right Now (Na Na Na).mp3",
      "Akon - Smack That.mp3",
      "Akon - So Blue.mp3",
      "Akon - Sorry Blame It On Me.mp3",
      "Akon - Sunny Day.mp3",
      "Akon - We Don't Care.mp3",
    ],
    artistID: 902
  },
  {
    path: "ali-gatie",
    artistName: "Ali Gatie",
    musics: [
      "Ali Gatie - Do You Believe.mp3",
      "Ali Gatie - How Things Used To Be.mp3",
      "Ali Gatie - It's You.mp3",
      "Ali Gatie - Moonlight.mp3",
      "Ali Gatie - What If I Told You That I Love You.mp3",
    ],
    artistID: 2,
  },
  {
    path: "ariana-grande",
    artistName: "Ariana Grande",
    musics: [
      "Ariana Grande - 34 + 35.mp3",
      "Ariana Grande - Break Free.mp3",
      "Ariana Grande - Dangerous Woman.mp3",
      "Ariana Grande - Positions.mp3",
      "Ariana Grande - 7 rings.mp3",
    ],
    artistID: 3,
  },
  {
    path: "arthur-nery",
    artistName: "Arthur Nery",
    musics: [
      "Arthur Nery - Binhi.mp3",
      "Arthur Nery - Pagsamo.mp3",
      "Arthur Nery - TAKE ALL THE LOVE.mp3",
    ],
    artistID: 4,
  },
  {
    path: "avicii",
    artistName: "Avicii",
    musics: [
      "Avicii - Addicted To You.mp3",
      "Avicii - Broken Arrows.mp3",
      "Avicii - Fades Away.mp3",
      "Avicii - For A Better Day.mp3",
      "Avicii - Friend Of Mine.mp3",
      "Avicii - Heaven.mp3",
      "Avicii - Hey Brother.mp3",
      "Avicii - I Could Be The One.mp3",
      "Avicii - Lay Me Down.mp3",
      "Avicii - Levels.mp3",
      "Avicii - Lonely Together.mp3",
      "Avicii - Pure Grinding.mp3",
      "Avicii - Silhouettes.mp3",
      "Avicii - SOS.mp3",
      "Avicii - Sunset Jesus.mp3",
      "Avicii - The Days.mp3",
      "Avicii - The Nights.mp3",
      "Avicii - Trouble.mp3",
      "Avicii - Waiting For Love.mp3",
      "Avicii - Wake Me Up.mp3",
      "Avicii - WithOut You.mp3",
      "Avicii - You Be Love.mp3",
    ],
    artistID: 5,
  },
  {
    path: "avril-lavigne",
    artistName: "Avril Lavigne",
    musics: [
      "Avril Lavigne - Breakaway.mp3",
      "Avril Lavigne - Complicated.mp3",
      "Avril Lavigne - Head Above Water.mp3",
      "Avril Lavigne - Here's To Never Growing Up.mp3",
      "Avril Lavigne - My Happy Ending.mp3",
      "Avril Lavigne - When You're Gone.mp3",
      "Avril Lavigne - Wish You Were Here.mp3",
    ],
    artistID: 6,
  },
  {
    path: "bazzi",
    artistName: "Bazzi",
    musics: [
      "Bazzi - Beautiful.mp3",
      "Bazzi - I.F.L.Y..mp3",
      "Bazzi - Mine.mp3",
      "Bazzi - Myself.mp3",
      "Bazzi - Paradise.mp3",
    ],
    artistID: 7,
  },
  {
    path: "beegees",
    artistName: "Beegees",
    musics: [
      "Beegees - Don't Forget To Remember.mp3",
      "Beegees - How Deep Is Your Love.mp3",
      "Beegees - I Started A Joke.mp3",
      "Beegees - Massachusetts.mp3",
      "Beegees - Night Fever.mp3",
      "Beegees - To Love Somebody.mp3",
      "Beegees - Too Much Heaven.mp3",
      "Beegees - Tragedy.mp3",
      "Beegees - Wish You Were Here.mp3",
    ],
    artistID: 1010,
  },
  {
    path: "ben&ben",
    artistName: "Ben&Ben",
    musics: [
      "Ben&Ben - Araw-Araw.mp3",
      "Ben&Ben - Bibingka.mp3",
      "Ben&Ben - Dear.mp3",
      "Ben&Ben - Di Ka Sayang.mp3",
      "Ben&Ben - Leaves.mp3",
      "Ben&Ben - Ben&Ben - Masyado Pang Maaga.mp3",
      "Ben&Ben - Maybe The Night.mp3",
      "Ben&Ben - Nakikinig ka ba sa Akin.mp3",
      "Ben&Ben - Pagtingin.mp3",
      "Ben&Ben - Pasalubong (feat. Moira Dela Torre).mp3",
      "Ben&Ben - Ride Home.mp3",
      "Ben&Ben - Sugat (feat. Munimuni).mp3",
    ],
    artistID: 8,
  },
  {
    path: "billie-eilish",
    artistName: "Billie Eilish",
    musics: [
      "Billie Eilish - Bad Guy.mp3",
      "Billie Eilish - Bellyache.mp3",
      "Billie Eilish - Bury A Friend.mp3",
      "Billie Eilish - Copycat.mp3",
      "Billie Eilish - Everything I Wanted.mp3",
      "Billie Eilish - Lovely.mp3",
      "Billie Eilish - Ocean Eyes.mp3",
      "Billie Eilish - sHE's brOKen.mp3",
      "Billie Eilish - Therefore I Am.mp3",
      "Billie Eilish - Watch.mp3",
      "Billie Eilish - When The Party's Over.mp3",
      "Billie Eilish - Wish You Were Gay.mp3",
      "Billie Eilish - Xanny.mp3",
      "Billie Eilish - You Should See Me In A Crown.mp3",
      "Billie Eilish - Your Power.mp3",
    ],
    artistID: 9,
  },
  {
    path: "blackpink",
    artistName: "BLACKPINK",
    musics: [
      "BLACKPINK - How You Like That.mp3",
      "BLACKPINK - Ice Cream.mp3",
      "BLACKPINK - Lovesick Girls.mp3",
    ],
    artistID: 10,
  },
  {
    path: "blink-182",
    artistName: "Blink-182",
    musics: [
      "Blink-182 - Adam's Song.mp3",
      "Blink-182 - All The Small Things.mp3",
      "Blink-182 - First Date.mp3",
      "Blink-182 - I Miss You.mp3",
      "Blink-182 - Stay Together For The Kids.mp3",
      "Blink-182 - What's My Age Again.mp3",
    ],
    artistID: 11,
  },
  {
    path: "bon-jovi",
    artistName: "Bon Jovi",
    musics: [
      "Bon Jovi - Bed Of Roses.mp3",
      "Bon Jovi - It's My Life.mp3",
      "Bon Jovi - Livin' On A Prayer.mp3",
    ],
    artistID: 12,
  },
  {
    path: "bruno-mars",
    artistName: "Bruno Mars",
    musics: [
      "Bruno Mars - Count On Me.mp3",
      "Bruno Mars - Grenade.mp3",
      "Bruno Mars - It Will Rain.mp3",
      "Bruno Mars - Just The Way You Are.mp3",
      "Bruno Mars - Locked Out Of Heaven.mp3",
      "Bruno Mars - That's What I Like.mp3",
      "Bruno Mars - Today My Life Begins.mp3",
      "Bruno Mars - Versace On The Floor.mp3",
    ],
    artistID: 13,
  },
  {
    path: "bruz",
    artistName: "BRUZ",
    musics: ["BRUZ - SHYBOI.mp3"],
    artistID: 14,
  },
  {
    path: "bryan-adams",
    artistName: "Bryan Adams",
    musics: [
      "Bryan Adams - (Everything I Do) I Do It For You.mp3",
      "Bryan Adams - Please Forgive Me.mp3",
      "Bryan Adams - Summer Of '69.mp3",
    ],
    artistID: 15,
  },
  {
    path: "cavetown",
    artistName: "Cavetown",
    musics: [
      "Cavetown - Feb 14.mp3",
      "Cavetown - Idea of Her.mp3",
      "Cavetown - Paul.mp3",
      "Cavetown - Sharpener.mp3",
      "Cavetown - Telescope.mp3",
      "Cavetown - Trying.mp3",
      "Cavetown - Wishing Well.mp3",
    ],
    artistID: 16,
  },
  {
    path: "charlie-puth",
    artistName: "Charlie Puth",
    musics: [
      "Charlie Puth - Attention.mp3",
      "Charlie Puth - How Long.mp3",
      "Charlie Puth - Kiss Me.mp3",
      "Charlie Puth - Up All Night.mp3",
      "Charlie Puth - We Don't Talk Anymore.mp3",
    ],
    artistID: 17,
  },
  {
    path: "chelsea-cutler",
    artistName: "Chelsea Cutler",
    musics: [
      "Chelsea Cutler - Are You Listening.mp3",
      "Chelsea Cutler - Parent song.mp3",
      "Chelsea Cutler - Sixteen.mp3",
      "Chelsea Cutler - The stars.mp3",
      "Chelsea Cutler - Your Shirt.mp3",
    ],
    artistID: 18,
  },
  {
    path: "chilledcow",
    artistName: "ChilledCow",
    musics: [
      "ChilledCow - 1 A.M Study Session - (lofi hip hop chill beats).mp3",
      "ChilledCow - 2 A.M Study Session - (lofi hip hop chill beats).mp3",
      "ChilledCow - 4 A.M Study Session - (lofi hip hop chill beats).mp3",
      "ChilledCow - Brillion. - Bedtime Stories.mp3",
      "ChilledCow - Casiio - Wondering.mp3",
      "ChilledCow - DLJ - Night Emotions.mp3",
      "ChilledCow - Dontcry x Glimlip - 777.mp3",
      "ChilledCow - Fatb - Conscious Ego.mp3",
      "ChilledCow - Idealism - Last Time.mp3",
      "ChilledCow - Kupla - Kingdom In Blue.mp3",
      "ChilledCow - Kupla - Life Forms.mp3",
      "ChilledCow - Lazy Sunday - (lofi hip hop chill beats).mp3",
      "ChilledCow - Mell-ø x Ambulo - Afloat Again.mp3",
      "ChilledCow - Monma - Calm Lands.mp3",
      "ChilledCow - Refeeld x Project AER - Chance Encounter.mp3",
      "ChilledCow - Tysu x Spencer Hunt - Window Seat.mp3",
    ],
    artistID: 19,
  },
  {
    path: "chillhop-music",
    artistName: "Chillhop Music",
    musics: [
      "Chillhop Music - Chillhop Essentials · Spring 2021 [instrumental beats compilation].mp3",
      "Chillhop Music - Chillhop Essentials · Summer 2021 [instrumental beats compilation].mp3",
      "Chillhop Music - Chillhop Essentials · Winter 2018 [lofi hip hop & chill beats].mp3",
      "Chillhop Music - Chillhop Yearmix 2018 [chillhop & lofi hip hop].mp3",
      "Chillhop Music - Chillhop Yearmix 2020 [instrumental beats & lofi hip hop].mp3",
      "Chillhop Music - Endless Sunday [Chillhop instrumental beats].mp3",
      "Chillhop Music - Endless Sunday 2 [lofi jazz instrumental hip hop beats].mp3",
    ],
    artistID: 20,
  },
  {
    path: "cigarettes-after-sex",
    artistName: "Cigarettes After Sex",
    musics: [
      "Cigarettes After Sex - Affection.mp3",
      "Cigarettes After Sex - Apocalypse.mp3",
      "Cigarettes After Sex - Dreaming Of You.mp3",
      "Cigarettes After Sex - Heavenly.mp3",
      "Cigarettes After Sex - K..mp3",
      "Cigarettes After Sex - Nothing's Gonna Hurt You Baby.mp3",
      "Cigarettes After Sex - Sweet.mp3",
    ],
    artistID: 21,
  },
  {
    path: "claire-cottrill",
    artistName: "Claire Cottrill",
    musics: [
      "Claire Cottrill - 4EVER.mp3",
      "Claire Cottrill - Bags.mp3",
      "Claire Cottrill - Bubble Gum.mp3",
      "Claire Cottrill - Pretty Girl.mp3",
      "Claire Cottrill - Sofia.mp3",
      "Claire Cottrill - Softly.mp3",
    ],
    artistID: 22,
  },
  {
    path: "claire-rosinkranz",
    artistName: "Claire Rosinkranz",
    musics: [
      "Claire Rosinkranz - Backyard Boy.mp3",
      "Claire Rosinkranz - BeVerly Hills BoYfRiEnd.mp3",
      "Claire Rosinkranz - Frankenstein.mp3",
      "Claire Rosinkranz - Real Life.mp3",
      "Claire Rosinkranz - Tough Guy.mp3",
    ],
    artistID: 23,
  },
  {
    path: "coldplay",
    artistName: "Coldplay",
    musics: [
      "Coldplay - Clocks.mp3",
      "Coldplay - Cry Cry Cry.mp3",
      "Coldplay - Fix You.mp3",
      "Coldplay - Higher Power.mp3",
      "Coldplay - In My Place.mp3",
      "Coldplay - O.mp3",
      "Coldplay - Paradise.mp3",
      "Coldplay - The Scientist.mp3",
      "Coldplay - Yellow.mp3",
    ],
    artistID: 24,
  },
  {
    path: "creed",
    artistName: "Creed",
    musics: [
      "Creed - My Sacrifice.mp3",
      "Creed - One Last Breath.mp3",
      "Creed - With Arms Wide Open.mp3",
    ],
    artistID: 25,
  },
  {
    path: "cueshe",
    artistName: "Cueshe",
    musics: [
      "Cueshe - 24 Hours.mp3",
      "Cueshe - Back To Me.mp3",
      "Cueshe - Borrowed Time.mp3",
      "Cueshe - Can't Let You Go.mp3",
      "Cueshe - Stay.mp3",
      "Cueshe - Ulan.mp3",
    ],
    artistID: 26,
  },
  {
    path: "daughtry",
    artistName: "Daughtry",
    musics: ["Daughtry - Home.mp3", "Daughtry - Over You.mp3"],
    artistID: 27,
  },
  {
    path: "december-avenue",
    artistName: "December Avenue",
    musics: [
      "December Avenue - Bulong.mp3",
      "December Avenue - Eroplanong Papel.mp3",
      "December Avenue - Kahit 'Di Mo Alam.mp3",
      "December Avenue - Magkunwari.mp3",
      "December Avenue - Sa Ngalan Ng Pag-Ibig.mp3",
    ],
    artistID: 28,
  },
  {
    path: "disturbed",
    artistName: "Disturbed",
    musics: [
      "Disturbed - Down With The Sickness.mp3",
      "Disturbed - Stupify.mp3",
      "Disturbed - The Sound Of Silence.mp3",
    ],
    artistID: 29,
  },
  {
    path: "drake",
    artistName: "Drake",
    musics: [
      "Drake - Find Your Love.mp3",
      "Drake - God's Plan.mp3",
      "Drake - Hotline Bling.mp3",
      "Drake - In My Feelings.mp3",
      "Drake - Laugh Now Cry Later.mp3",
      "Drake - Over My Dead Body.mp3",
      "Drake - Over.mp3",
      "Drake - Rich Flex.mp3",
      "Drake - Toosie Slide.mp3",
      "Drake - Trust Issues.mp3",
    ],
    artistID: 29,
  },
  {
    path: "dreamy",
    artistName: "Dreamy",
    musics: [
      "Dreamy - Because music cures every problem ~ lofi hip hop mix.mp3",
      "Dreamy - Believe in the dream ~ lofi hip hop mix.mp3",
      "Dreamy - Breathing dreams like air ~ lofi hip hop mix.mp3",
      "Dreamy - Dream keeps me alive ~ lofi hip hop mixconv.mp3",
      "Dreamy - Guitar Vibe ~ lofi hip hop mix.mp3",
      "Dreamy - It's 2am. I need you here ~ lofi hip hop mix.mp3",
      "Dreamy - Let's just stay here forever ~ lofi hip hop mix.mp3",
      "Dreamy - Lullaby to the Stars ~ lofi hip hop mix - study beats.mp3",
      "Dreamy - Night walks on the rooftops ~ lofi relax stress relief.mp3",
      "Dreamy - Raining day ~ lofi hip hop mix.mp3",
      "Dreamy - Solitude ~ lofi hip hop mix.mp3",
      "Dreamy - Stay with me ~ lofi hip hop mix.mp3",
      "Dreamy - Your smile — My everything ~ lofi hip hop mix.mp3",
      "Dreamy - Yūgen ~ Japanese Lofi Hip-Hop.mp3",
      "Dreamy - Because music cures every problem ~ lofi hip hop mix.mp3",
    ],
    artistID: 30,
  },
  {
    path: "e-ve",
    artistName: "E ve",
    musics: [
      "E ve - Dramaturgy.mp3",
      "E ve - Heart Forecast.mp3",
      "E ve - YORUWA HONOKA (Night is Faint).mp3",
      "E ve - 平行線.mp3",
      "E ve - 廻廻奇譚.mp3",
      "E ve - 群青讃歌.mp3",
      "E ve - 蒼のワルツ.mp3",
      "E ve - 遊生夢死(Living idly and dying as if dreaming).mp3",
    ],
    artistID: 31,
  },
  {
    path: "ed-sheeran",
    artistName: "Ed Sheeran",
    musics: [
      "Ed Sheeran - Afterglow.mp3",
      "Ed Sheeran - Barcelona.mp3",
      "Ed Sheeran - Castle On The Hill.mp3",
      "Ed Sheeran - Dive.mp3",
      "Ed Sheeran - How Would You Feel.mp3",
      "Ed Sheeran - Perfect.mp3",
      "Ed Sheeran - Photograph.mp3",
      "Ed Sheeran - Shape Of You.mp3",
    ],
    artistID: 32,
  },
  {
    path: "eminem",
    artistName: "Eminem",
    musics: [
      "Eminem - Deep End.mp3",
      "Eminem - Lose Your Self.mp3",
      "Eminem - Love The Way You Lie.mp3",
      "Eminem - River.mp3",
      "Eminem - The Monster.mp3",
      "Eminem - The Real Slim Shady.mp3",
    ],
    artistID: 33,
  },
  {
    path: "emman",
    artistName: "EMMAN",
    musics: [
      "EMMAN - Kung Pwede Lang.mp3",
      "EMMAN - Teka Lang.mp3",
      "EMMAN - Uuwian.mp3",
    ],
    artistID: 34,
  },
  {
    path: "eraserheads",
    artistName: "Eraserheads",
    musics: [
      "Eraserheads - Alapaap.mp3",
      "Eraserheads - Ang Huling El Bimbo.mp3",
      "Eraserheads - Harana.mp3",
      "Eraserheads - Huwag Kang Matakot.mp3",
      "Eraserheads - Huwag Mo Nang Itanong.mp3",
      "Eraserheads - Kailan.mp3",
      "Eraserheads - Ligaya.mp3",
      "Eraserheads - Magasin.mp3",
      "Eraserheads - Maling Akala.mp3",
      "Eraserheads - Maselang Bahaghari.mp3",
      "Eraserheads - Minsan.mp3",
      "Eraserheads - Pare Ko.mp3",
      "Eraserheads - Sembreak.mp3",
      "Eraserheads - Spoliarium.mp3",
      "Eraserheads - Tindahan Ni Aling Nena.mp3",
      "Eraserheads - Toyang.mp3",
      "Eraserheads - Trip To Jerusalem.mp3",
      "Eraserheads - With A Smile.mp3",
    ],
    artistID: 35,
  },
  {
    path: "evanescence",
    artistName: "Evanescence",
    musics: [
      "Evanescence - Bring Me To Life.mp3",
      "Evanescence - Going Under.mp3",
      "Evanescence - My Immortal.mp3",
    ],
    artistID: 36,
  },
  {
    path: "finding-hope",
    artistName: "Finding Hope",
    musics: [
      "Finding Hope - 3 AM.mp3",
      "Finding Hope - Heaven.mp3",
      "Finding Hope - Love.mp3",
      "Finding Hope - More & More.mp3",
      "Finding Hope - Strangers.mp3",
      "Finding Hope - Valentine's Day.mp3",
      "Finding Hope - Without You.mp3",
    ],
    artistID: 37,
  },
  {
    path: "five-for-fighting",
    artistName: "Five For Fighting",
    musics: [
      "Five for Fighting - 100 Years.mp3",
      "Five for Fighting - Superman.mp3",
      "Five for Fighting - The Riddle.mp3",
    ],
    artistID: 38,
  },
  {
    path: "fm-static",
    artistName: "Fm Static",
    musics: [
      "FM Static - Moment Of Truth.mp3",
      "FM Static - Tonight.mp3",
      "FM Static - What It Feels Like.mp3",
    ],
    artistID: 39,
  },
  {
    path: "藤井-風-(fujii-kaze)",
    artistName: "藤井 風 (Fujii Kaze)",
    musics: [
      "藤井 風 (Fujii Kaze) - もうええわ (Mo-Eh-Wa).mp3",
      "藤井 風 (Fujii Kaze) - 優しさ (YASASHISA).mp3",
      "藤井 風 (Fujii Kaze) - 帰ろう (Kaerou).mp3",
      "藤井 風 (Fujii Kaze) - 旅路 (Tabiji).mp3",
    ],
    artistID: 40,
  },
  {
    path: "gian",
    artistName: "GIAN",
    musics: ["GIAN - Tayo.mp3"],
    artistID: 41,
  },
  {
    path: "giveon",
    artistName: "Giveon",
    musics: [
      "Giveon - All To Me.mp3",
      "Giveon - Favorite Mistake.mp3",
      "Giveon - For Tonight.mp3",
      "Giveon - Heartbreak Anniversary.mp3",
      "Giveon - Like I Want You.mp3",
      "Giveon - Still Your Best.mp3",
      "Giveon - Stuck On You.mp3",
      "Giveon - Take Time (Interlude).mp3",
      "Giveon - The Beach.mp3",
      "Giveon - This Ain't Love.mp3",
      "Giveon - VANISH.mp3",
      "Giveon - WORLD WE CREATED.mp3",
    ],
    artistID: 42,
  },
  {
    path: "green-day",
    artistName: "Green Day",
    musics: [
      "Green Day - 21 Guns.mp3",
      "Green Day - Basket Case.mp3",
      "Green Day - Boulevard Of Broken Dreams.mp3",
      "Green Day - Holiday.mp3",
      "Green Day - Wake Me Up When September Ends.mp3",
    ],
    artistID: 43,
  },
  {
    path: "guns-n'-roses",
    artistName: "Guns N' Roses",
    musics: [
      "Guns N' Roses - November Rain.mp3",
      "Guns N' Roses - Patience.mp3",
      "Guns N' Roses - Sweet Child O' Mine.mp3",
      "Guns N' Roses - Welcome To The Jungle.mp3",
    ],
    artistID: 44,
  },
  {
    path: "halsey",
    artistName: "Halsey",
    musics: [
      "Halsey - 3AM.mp3",
      "Halsey - Alone.mp3",
      "Halsey - Colors.mp3",
      "Halsey - Eastside.mp3",
      "Halsey - Without Me.mp3",
    ],
    artistID: 45,
  },
  {
    path: "harry-styles",
    artistName: "Harry Styles",
    musics: [
      "Harry Styles - Adore You.mp3",
      "Harry Styles - As It Was.mp3",
      "Harry Styles - Daylight.mp3",
      "Harry Styles - Falling.mp3",
      "Harry Styles - Golden.mp3",
      "Harry Styles - Kiwi.mp3",
      "Harry Styles - Late Night Talking.mp3",
      "Harry Styles - Music For a Sushi Restaurant.mp3",
      "Harry Styles - Satellite.mp3",
      "Harry Styles - Sign of the Times.mp3"
    ],
    artistID: 901,
  },
  {
    path: "hinder",
    artistName: "Hinder",
    musics: [
      "Hinder - Better Than Me.mp3",
      "Hinder - Lips Of An Angel.mp3",
      "Hinder - Without You.mp3",
    ],
    artistID: 46,
  },
  {
    path: "hoobastank",
    artistName: "Hoobastank",
    musics: [
      "Hoobastank - Crawling In The Dark.mp3",
      "Hoobastank - Running Away.mp3",
      "Hoobastank - The Reason.mp3",
    ],
    artistID: 47,
  },
  {
    path: "imaginedragons",
    artistName: "ImagineDragons",
    musics: [
      "ImagineDragons - Bad Liar.mp3",
      "ImagineDragons - Believer.mp3",
      "ImagineDragons - Birds.mp3",
      "ImagineDragons - Natural.mp3",
      "ImagineDragons - Next To Me.mp3",
      "ImagineDragons - Whatever It Takes.mp3",
    ],
    artistID: 48,
  },
  {
    path: "iv-of-spades",
    artistName: "IV of Spades",
    musics: [
      "IV OF SPADES - Ang Pinagmulan.mp3",
      "IV OF SPADES - Bawat Kaluluwa.mp3",
      "IV OF SPADES - Hey Barbara.mp3",
      "IV OF SPADES - Ilaw Sa Daan.mp3",
      "IV OF SPADES - Mundo.mp3",
    ],
    artistID: 49,
  },
  {
    path: "jason-derulo",
    artistName: "Jason Derulo",
    musics: [
      "Jason Derulo - In My Head.mp3",
      "Jason Derulo - It Girl.mp3",
      "Jason Derulo - Love Not War.mp3",
      "Jason Derulo - Marry Me.mp3",
      "Jason Derulo - Ridin Solo.mp3",
      "Jason Derulo - Stupid Love.mp3",
      "Jason Derulo - Swalla.mp3",
      "Jason Derulo - Talk Dirty.mp3",
      "Jason Derulo - Trumpets.mp3",
      "Jason Derulo - Want To Want Me.mp3",
      "Jason Derulo - Whatcha Say.mp3",
    ],
    artistID: 49,
  },
  {
    path: "jay-z",
    artistName: "Jay Z",
    musics: [
      "JAY Z -  Lost One.mp3",
      "JAY Z - 03 Bonnie and Clyde.mp3",
      "JAY Z - Change Clothes.mp3",
      "JAY Z - Come and Get Me.mp3",
      "JAY Z - Do It Again.mp3",
      "JAY Z - Dope Man.mp3",
      "JAY Z - Empire State Of Mind.mp3",
      "JAY Z - Holy Grail.mp3",
      "JAY Z - Linkin Park Numb and Encore.mp3",
      "JAY Z - Run This Town.mp3",
      "JAY Z - Show Me What You Got.mp3",
      "JAY Z - So Ghetto.mp3",
      "JAY Z - Song Cry.mp3",
      "JAY Z - The Story of O.J.mp3",
      "JAY Z - Things That U Do.mp3",
      "JAY Z - Watch Me.mp3",
      "JAY Z - Young Forever.mp3",
      "Jay-Z - Bam.mp3",
      "JAY-Z - Change The Game.mp3",
    ],
    artistID: 49,
  },
  {
    path: "joji",
    artistName: "Joji",
    musics: [
      "Joji -  Glimpse of Us.mp3",
      "Joji - 1AM FREESTYLE.mp3",
      "Joji - 777.mp3",
      "Joji - Afterthought.mp3",
      "Joji - ATTENTION.mp3",
      "Joji - Before The Day Is Over.mp3",
      "Joji - BLAHBLAHBLAH DEMO.mp3",
      "Joji - Daylight.mp3",
      "Joji - Die For You.mp3",
      "Joji - Dissolve.mp3",
      "Joji - Ew.mp3",
      "Joji - Feeling Like The End.mp3",
      "Joji - Glimpse of Us.mp3",
      "Joji - Like You Do.mp3",
      "Joji - MODUS.mp3",
      "Joji - Mr. Hollywood.mp3",
      "Joji - NIGHT RIDER.mp3",
      "Joji - Run.mp3",
      "Joji - Sanctuary.mp3",
      "Joji - slow dancing in the dark.mp3",
      "Joji - Tick Tock.mp3",
      "Joji - Upgrade.mp3",
      "Joji - XNXX.mp3",
      "Joji - YEAH RIGHT.mp3",
      "Joji - Your Man.mp3",
      "Joji - YUKON.mp3"
    ],
    artistID: 50,
  },
  {
    path: "juice-wrld",
    artistName: "Juice WRLD",
    musics: [
      "Juice WRLD - Empty.mp3",
      "Juice WRLD - Lucid Dreams.mp3",
      "Juice WRLD - Real Shit.mp3",
      "Juice WRLD - Reminds Me Of You.mp3",
      "Juice WRLD - Robbery.mp3",
      "Juice WRLD - sad.mp3",
      "Juice WRLD - Smile.mp3",
      "Juice WRLD - Wishing Well.mp3",
    ],
    artistID: 51,
  },
  {
    path: "just-hush",
    artistName: "Just Hush",
    musics: [
      "Just Hush - B.O.Y.M feat. OJ River.mp3",
      "Just Hush - bkrgrl.mp3",
      "Just Hush - Co-Pilot.mp3",
      "Just Hush - Iraya.mp3",
      "Just Hush - Maikees Letters.mp3",
      "Just Hush - Masiram Feat. Paul Royale.mp3",
      "Just Hush - Red Planet.mp3",
      "Just Hush - SHINOBI.mp3",
    ],
    artistID: 1000,
  },
  {
    path: "justin-timberlake",
    artistName: "Justin Timberlake",
    musics: [
      "Justin Timberlake - Can't Stop the Feeling.mp3",
      "Justin Timberlake - Mirrors.mp3",
      "Justin Timberlake - True Colors.mp3",
    ],
    artistID: 52,
  },
  {
    path: "kamikazee",
    artistName: "Kamikazee",
    musics: [
      "Kamikazee - Chiksilog.mp3",
      "Kamikazee - Doo Bidoo.mp3",
      "Kamikazee - Huling Sayaw (feat. Kyla).mp3",
      "Kamikazee - Kislap.mp3",
      "Kamikazee - Martyr Nyebera.mp3",
      "Kamikazee - Meron Akong Ano.mp3",
      "Kamikazee - Narda.mp3",
      "Kamikazee - Seksi! Seksi!.mp3",
      "Kamikazee - Tsinelas.mp3",
      "Kamikazee - Unang Tikim.mp3",
    ],
    artistID: 53,
  },
  {
    path: "kesha",
    artistName: "Kesha",
    musics: [
      "Kesha - Animal.mp3",
      "Kesha - Blah Blah Blah.mp3",
      "Kesha - Cannibal.mp3",
      "Kesha - Die Young.mp3",
      "Kesha - High Road.mp3",
      "Kesha - Praying.mp3",
      "Kesha - Raising Hell.mp3",
      "Kesha - Take It Off.mp3",
      "Kesha - TiK ToK.mp3",
      "Kesha - We R Who We R.mp3",
      "Kesha - Woman.mp3",
      "Kesha - Your Love Is My Drug.mp3",
    ],
    artistID: 53,
  },
  {
    path: "khalid",
    artistName: "Khalid",
    musics: [
      "Khalid - 8TEEN.mp3",
      "Khalid - Better.mp3",
      "Khalid - Location.mp3",
      "Khalid - OTW.mp3",
      "Khalid - Saturday Nights.mp3",
      "Khalid - Talk.mp3",
      "Khalid - Young Dumb & Broke.mp3",
    ],
    artistID: 54,
  },
  {
    path: "kiyo",
    artistName: "Kiyo",
    musics: [
      "Kiyo - Ano Na.mp3",
      "Kiyo - G Feat. Space Moses.mp3",
      "Kiyo - Ikaw Lang.mp3",
      "Kiyo - lust after love ft. shiloh.mp3",
      "Kiyo - not even her ft. shiloh.mp3",
      "Kiyo - sakay.mp3",
      "Kiyo - untitled ft shiloh.mp3",
      "Kiyo - Urong; Sulong.mp3",
    ],
    artistID: 55,
  },
  {
    path: "lady-gaga",
    artistName: "Lady Gaga",
    musics: [
      "Lady Gaga - Alejandro.mp3",
      "Lady Gaga - Always Remember Us This Way.mp3",
      "Lady Gaga - Americano.mp3",
      "Lady Gaga - Applause.mp3",
      "Lady Gaga - Bad Romance.mp3",
      "Lady Gaga - Born This Way.mp3",
      "Lady Gaga - Paparazzi.mp3",
      "Lady Gaga - Poker Face.mp3",
      "Lady Gaga - Shallow.mp3",
      "Lady Gaga - Telephone.mp3",
      "Lady Gaga - The Edge Of Glory.mp3",
      "Lady Gaga - Yoü And I.mp3",
    ],
    artistID: 56,
  },
  {
    path: "lany",
    artistName: "LANY",
    musics: [
      "LANY - 13.mp3",
      "LANY - Good Guys.mp3",
      "LANY - Hericane.mp3",
      "LANY - If this is the last time.mp3",
      "LANY - ILYSB.mp3",
      "LANY - Malibu Nights.mp3",
      "LANY - Super Far.mp3",
      "LANY - Valentine's Day.mp3",
      "LANY - you!.mp3",
    ],
    artistID: 57,
  },
  {
    path: "lauv",
    artistName: "Lauv",
    musics: [
      "Lauv - Getting Over You.mp3",
      "Lauv - I Like Me Better.mp3",
      "Lauv - Paris In The Rain.mp3",
    ],
    artistID: 58,
  },
  {
    path: "lil-uzi-vert",
    artistName: "Lil Uzi Vert",
    musics: [
      "Lil Uzi Vert - 7AM.mp3",
      "Lil Uzi Vert - 20 Min.mp3",
      "Lil Uzi Vert - Do What I Want.mp3",
      "Lil Uzi Vert - Go Off.mp3",
      "Lil Uzi Vert - Money Longer.mp3",
      "Lil Uzi Vert - Sauce It Up.mp3",
      "Lil Uzi Vert - That Way.mp3",
      "Lil Uzi Vert - The Way Life Goes.mp3",
      "Lil Uzi Vert - Top.mp3",
      "Lil Uzi Vert - XO Tour Llif3.mp3",
      "Lil Uzi Vert - Yessirskiii ft. 21 Savage.mp3",
      "Lil Uzi Vert - You Was Right.mp3",
    ],
    artistID: 59,
  },
  {
    path: "linkin-park",
    artistName: "Linkin Park",
    musics: [
      "Linkin Park - Bleed It Out.mp3",
      "Linkin Park - In The End.mp3",
      "Linkin Park - Numb.mp3",
    ],
    artistID: 60,
  },
  {
    path: "lowly",
    artistName: "Lowly",
    musics: [
      "Lowly - INZO - Angst.mp3",
      "Lowly - INZO - Overthinker.mp3",
      "Lowly - LIHO - Surrender.mp3",
    ],
    artistID: 61,
  },
  {
    path: "maroon-5",
    artistName: "Maroon 5",
    musics: [
      "Maroon 5 - Animals.mp3",
      "Maroon 5 - Cold.mp3",
      "Maroon 5 - Maps.mp3",
      "Maroon 5 - Payphone.mp3",
      "Maroon 5 - Sugar.mp3",
      "Maroon 5 - Won't Go Home Without You.mp3",
    ],
    artistID: 62,
  },
  {
    path: "marshmello",
    artistName: "Marshmello",
    musics: [
      "Marshmello - Alone.mp3",
      "Marshmello - Be Kind.mp3",
      "Marshmello - FLY.mp3",
      "Marshmello - FRIENDS.mp3",
      "Marshmello - Keep It Mello.mp3",
      "Marshmello - Room To Fall.mp3",
      "Marshmello - Spotlight.mp3",
      "Marshmello - Take It Back.mp3",
    ],
    artistID: 63,
  },
  {
    path: "michael-bublé",
    artistName: "Michael Bublé",
    musics: [
      "Michael Bublé - Always On My Mind.mp3",
      "Michael Bublé - Christmas Exclusive First Listen.mp3",
      "Michael Bublé - Everything.mp3",
      "Michael Bublé - Feeling Good.mp3",
      "Michael Bublé - Haven't Met You Yet.mp3",
      "Michael Bublé - Home.mp3",
      "Michael Bublé - It's A Beautiful Day.mp3",
      "Michael Bublé - Love You Anymore.mp3",
      "Michael Bublé - Me and Mrs. Jones.mp3",
    ],
    artistID: 64,
  },
  {
    path: "mike-posner",
    artistName: "Mike Posner",
    musics: [
      "Mike Posner - Be As You Are.mp3",
      "Mike Posner - Bow Chicka Wow Wow.mp3",
      "Mike Posner - I Took A Pill In Ibiza.mp3",
      "Mike Posner - Nothing Is Wrong.mp3",
      "Mike Posner - Please Don't Go.mp3",
    ],
    artistID: 65,
  },
  {
    path: "miley-cyrus",
    artistName: "Miley Cyrus",
    musics: [
      "Miley Cyrus - Malibu.mp3",
      "Miley Cyrus - Party In The U.S.A..mp3",
      "Miley Cyrus - We Can't Stop.mp3",
      "Miley Cyrus - Wrecking Ball.mp3",
    ],
    artistID: 66,
  },
  {
    path: "mrld",
    artistName: "mrld",
    musics: [
      "mrld - Ikaw Pa Rin.mp3",
      "mrld - Just Because.mp3",
      "mrld - Ligaya.mp3",
      "mrld - Maligayang Pagkunwari.mp3",
    ],
    artistID: 1001,
  },
  {
    path: "munimuni",
    artistName: "Munimuni",
    musics: [
      "Munimuni - Alat.mp3",
      "Munimuni - Ambag Ko.mp3",
      "Munimuni - Bawat Piyesa.mp3",
      "Munimuni - Bukas Makalawa.mp3",
      "Munimuni - Kalachuchi.mp3",
      "Munimuni - Kasama Kita.mp3",
      "Munimuni - Maligaya.mp3",
      "Munimuni - Marilag.mp3",
      "Munimuni - Nawa.mp3",
      "Munimuni - Oras.mp3",
      "Munimuni - Sa Hindi Pag-alala.mp3",
      "Munimuni - Sa'yo.mp3",
      "Munimuni - Simula.mp3",
      "Munimuni - Tahanan.mp3",
      "Munimuni - Tinig.mp3",
    ],
    artistID: 67,
  },
  {
    path: "my-chemical-romance",
    artistName: "My Chemical Romance",
    musics: [
      "My Chemical Romance - Disenchanted.mp3",
      "My Chemical Romance - Famous Last Words.mp3",
      "My Chemical Romance - Helena.mp3",
      "My Chemical Romance - I Don't Love You.mp3",
      "My Chemical Romance - Teenagers.mp3",
      "My Chemical Romance - The World Is Ugly.mp3",
      "My Chemical Romance - Welcome To The Black Parade.mp3",
    ],
    artistID: 68,
  },
  {
    path: "ne-yo",
    artistName: "Ne Yo",
    musics: [
      "Ne Yo - Because Of You.mp3",
      "Ne Yo - Closer.mp3",
      "Ne Yo - Go On Girl.mp3",
      "Ne Yo - Mad.mp3",
      "Ne Yo - Miss Independent.mp3",
      "Ne Yo - One In A Million.mp3",
      "Ne Yo - Sexy Love.mp3",
      "Ne Yo - So Sick.mp3",
    ],
    artistID: 68,
  },
  {
    path: "oasis",
    artistName: "Oasis",
    musics: [
      "Oasis - Don't Go Away.mp3",
      "Oasis - Don't Look Back In Anger.mp3",
      "Oasis - Stand By Me.mp3",
      "Oasis - Stop Crying Your Heart Out.mp3",
      "Oasis - Wonderwall.mp3",
    ],
    artistID: 69,
  },
  {
    path: "oh-wonder",
    artistName: "Oh Wonder",
    musics: [
      "Oh Wonder - Drive.mp3",
      "Oh Wonder - Hallelujah.mp3",
      "Oh Wonder - I Wish I Never Met You.mp3",
      "Oh Wonder - In And Out Of Love.mp3",
      "Oh Wonder - Ultralife.mp3",
      "Oh Wonder - Without You.mp3",
    ],
    artistID: 70,
  },
  {
    path: "olivia-rodrigo",
    artistName: "Olivia Rodrigo",
    musics: [
      "Olivia Rodrigo - All I Want.mp3",
      "Olivia Rodrigo - deja vu.mp3",
      "Olivia Rodrigo - drivers license.mp3",
      "Olivia Rodrigo - favorite crime.mp3",
      "Olivia Rodrigo - happier.mp3",
      "Olivia Rodrigo - hope ur ok.mp3",
      "Olivia Rodrigo - traitor.mp3",
    ],
    artistID: 71,
  },
  {
    path: "one-direction",
    artistName: "One Direction",
    musics: [
      "One Direction - Drag Me Down.mp3",
      "One Direction - Gotta Be You.mp3",
      "One Direction - History.mp3",
      "One Direction - One Thing.mp3",
      "One Direction - Steal My Girl.mp3",
      "One Direction - Story of My Life.mp3",
      "One Direction - What Makes You Beautiful.mp3",
      "One Direction - You and I.mp3",
    ],
    artistID: 72,
  },
  {
    path: "onerepublic",
    artistName: "OneRepublic",
    musics: [
      "OneRepublic - Counting Stars.mp3",
      "OneRepublic - Good Life.mp3",
      "OneRepublic - If I Lose Myself.mp3",
    ],
    artistID: 73,
  },
  {
    path: "owl-city",
    artistName: "Owl City",
    musics: [
      "Owl City - Always.mp3",
      "Owl City - Fireflies.mp3",
      "Owl City - Vanilla Twilight.mp3",
    ],
    artistID: 74,
  },
  {
    path: "paramore",
    artistName: "Paramore",
    musics: [
      "Paramore - Ain't It Fun.mp3",
      "Paramore - Brick By Boring Brick.mp3",
      "Paramore - CrushCrushCrush.mp3",
      "Paramore - Decode.mp3",
      "Paramore - Hard Times.mp3",
      "Paramore - Ignorance.mp3",
      "Paramore - Last Hope.mp3",
      "Paramore - Monster.mp3",
      "Paramore - My Heart.mp3",
      "Paramore - Still Into You.mp3",
      "Paramore - That's What You Get.mp3",
      "Paramore - The Only Exception.mp3",
      "Paramore - Turn It Off.mp3",
      "Paramore - When It Rains.mp3",
    ],
    artistID: 75,
  },
  {
    path: "parokya-ni-edgar",
    artistName: "Parokya Ni Edgar",
    musics: [
      "Parokya Ni Edgar - Alumni Homecoming.mp3",
      "Parokya Ni Edgar - Bagsakan.mp3",
      "Parokya Ni Edgar - Barkada.mp3",
      "Parokya Ni Edgar - Buloy.mp3",
      "Parokya Ni Edgar - Gitara.mp3",
      "Parokya Ni Edgar - Halaga.mp3",
      "Parokya Ni Edgar - Harana.mp3",
      "Parokya Ni Edgar - Mang Jose.mp3",
      "Parokya Ni Edgar - Papa Cologne.mp3",
      "Parokya Ni Edgar - Para Sa'yo.mp3",
      "Parokya Ni Edgar - Picha Pie.mp3",
      "Parokya Ni Edgar - Saan Man Patungo.mp3",
      "Parokya Ni Edgar - Sampip.mp3",
      "Parokya Ni Edgar - Sayang.mp3",
      "Parokya Ni Edgar - Silvertoes.mp3",
      "Parokya Ni Edgar - Wag Mo Na Sana.mp3",
      "Parokya Ni Edgar - Your Song.mp3",
    ],
    artistID: 76,
  },
  {
    path: "planetshakers",
    artistName: "PlanetShakers",
    musics: [
      "Planetshakers - All About You.mp3",
      "Planetshakers - Born to Praise.mp3",
      "Planetshakers - Bring It On.mp3",
      "Planetshakers - Dance.mp3",
      "Planetshakers - I'm Forever Yours.mp3",
      "Planetshakers - Nothing Is Impossible.mp3",
    ],
    artistID: 77,
  },
  {
    path: "post-malone",
    artistName: "Post Malone",
    musics: [
      "Post Malone - Better Now.mp3",
      "Post Malone - Broken Whiskey Glass.mp3",
      "Post Malone - Circles.mp3",
      "Post Malone - Congratulations.mp3",
      "Post Malone - Deja Vu.mp3",
      "Post Malone - Feel.mp3",
      "Post Malone - Go Flex.mp3",
      "Post Malone - Goodbyes.mp3",
      "Post Malone - I Fall Apart.mp3",
      "Post Malone - No Option.mp3",
      "Post Malone - Patient.mp3",
      "Post Malone - Psycho.mp3",
      "Post Malone - Sunflower.mp3",
      "Post Malone - Too Young.mp3",
      "Post Malone - Up There.mp3",
      "Post Malone - White Iverson.mp3",
      "Post Malone - Yours Truly, Austin Post.mp3",
    ],
    artistID: 78,
  },
  {
    path: "powfu",
    artistName: "Powfu",
    musics: [
      "Powfu - a castle by the sea.mp3",
      "Powfu - A world of chaos.mp3",
      "Powfu - Days we had.mp3",
      "Powfu - Death bed.mp3",
      "Powfu - Don't fall asleep yet.mp3",
      "Powfu - future diary.mp3",
      "Powfu - I can't sleep.mp3",
      "Powfu - I know you're not happy.mp3",
      "Powfu - ice heart.mp3",
      "Powfu - Jomie, Skinny Atlas - future diary.mp3",
      "Powfu - Letters in december.mp3",
      "Powfu - Life is Changing.mp3",
      "Powfu - Life with you.mp3",
      "Powfu - long fights, short tempers..mp3",
      "Powfu - Sara Kays, Sarcastic Sounds - the long way home.mp3",
      "Powfu - snowflake ft. Jaden, Sarcastic Sounds.mp3",
      "Powfu - stay4ever.mp3",
      "Powfu - Step into my life.mp3",
      "Powfu - Talk Tomorrow.mp3",
      "Powfu - the long way home.mp3",
      "powfu - The way that you see me.mp3",
      "Powfu - Travis Barker - mario kart.mp3",
      "Powfu - When the hospital was my home.mp3",
      "Powfu - Would look perfect.mp3",
    ],
    artistID: 79,
  },
  {
    path: "public",
    artistName: "Public",
    musics: ["Public - Make You Mine.mp3"],
    artistID: 80,
  },
  {
    path: "queen",
    artistName: "Queen",
    musics: [
      "Queen - Another One Bites the Dust.mp3",
      "Queen - Bohemian Rhapsody.mp3",
      "Queen - Crazy Little Thing Called Love.mp3",
      "Queen - I Want To Break Free.mp3",
      "Queen - Radio Ga Ga.mp3",
      "Queen - Somebody To Love.mp3",
      "Queen - Under Pressure.mp3",
      "Queen - We Are The Champions .mp3",
      "Queen - We Will Rock You.mp3",
      "Queen - Who Wants To Live Forever.mp3",
    ],
    artistID: 81,
  },
  {
    path: "radwimps",
    artistName: "RADWIMPS",
    musics: [
      "RADWIMPS - Nandemonaiya.mp3",
      "RADWIMPS - Sparkle.mp3",
      "RADWIMPS - 前前前世 (Zen Zen Zense).mp3",
    ],
    artistID: 82,
  },
  {
    path: "red-hot-chili-peppers",
    artistName: "Red Hot Chili Peppers",
    musics: [
      "Red Hot Chili Peppers - Californication.mp3",
      "Red Hot Chili Peppers - Otherside.mp3",
      "Red Hot Chili Peppers - Scar Tissue.mp3",
    ],
    artistID: 83,
  },
  {
    path: "rex-orange-county",
    artistName: "Rex Orange County",
    musics: [
      "Rex Orange County - Best Friend.mp3",
      "Rex Orange County - Happiness.mp3",
      "Rex Orange County - Loving is Easy.mp3",
      "Rex Orange County - Sunflower.mp3",
    ],
    artistID: 84,
  },
  {
    path: "ricky-montgomery",
    artistName: "Ricky Montgomery",
    musics: [
      "Ricky Montgomery - California.mp3",
      "Ricky Montgomery - Line Without a Hook.mp3",
      "Ricky Montgomery - Mr Loverman.mp3",
      "Ricky Montgomery - My Heart Is Buried In Venice.mp3",
      "Ricky Montgomery - Snow.mp3",
      "Ricky Montgomery - Sorry for Me.mp3",
    ],
    artistID: 85,
  },
  {
    path: "rihanna",
    artistName: "Rihanna",
    musics: [
      "Rihanna - California King Bed.mp3",
      "Rihanna - Diamonds.mp3",
      "Rihanna - Disturbia.mp3",
      "Rihanna - Don't Stop The Music.mp3",
      "Rihanna - Kiss It Better.mp3",
      "Rihanna - Lift Me Up.mp3",
      "Rihanna - Rehab.mp3",
      "Rihanna - Take A Bow.mp3",
      "Rihanna - Te Amo.mp3",
      "Rihanna - Umbrella.mp3",
      "Rihanna - Unfaithful.mp3",
      "Rihanna - We Found Love.mp3",
      "Rihanna - What Now.mp3",
      "Rihanna - Where Have You Been.mp3",
      "Rihanna - Work.mp3",
    ],
    artistID: 85,
  },
  {
    path: "rini",
    artistName: "RINI",
    musics: [
      "RINI - Aphrodite.mp3",
      "RINI - Meet Me in Amsterdam.mp3",
      "RINI - Oceane ft. Olivia Escuyos.mp3",
    ],
    artistID: 86,
  },
  {
    path: "rivermaya",
    artistName: "Rivermaya",
    musics: [
      "Rivermaya - 214.mp3",
      "Rivermaya - 241.mp3",
      "Rivermaya - Awit ng Kabataan.mp3",
      "Rivermaya - Balisong.mp3",
      "Rivermaya - Elesi.mp3",
      "Rivermaya - Himala.mp3",
      "Rivermaya - Hinahanap-Hanap Kita.mp3",
      "Rivermaya - If.mp3",
      "Rivermaya - Isang Bandila.mp3",
      "Rivermaya - Kisapmata.mp3",
      "Rivermaya - Liwanag Sa Dilim.mp3",
      "Rivermaya - Luha.mp3",
      "Rivermaya - Panahon Na Naman.mp3",
      "Rivermaya - Umaaraw Umuulan.mp3",
      "Rivermaya - You'll Be Safe Here.mp3",
    ],
    artistID: 86,
  },
  {
    path: "russ",
    artistName: "Russ",
    musics: [
      "Russ - 3_15 (Breathe).mp3",
      "Russ - AINT GOIN BACK.mp3",
      "Russ - Are You Entertained.mp3",
      "Russ - Begging You.mp3",
      "Russ - BET.mp3",
      "Russ - Got This.mp3",
      "Russ - Last Night.mp3",
      "Russ - Losin Control Pt. 2.mp3",
      "Russ - Losin Control.mp3",
      "Russ - Me You.mp3",
      "Russ - Missin You Crazy.mp3",
      "Russ - Nobody Knows.mp3",
      "Russ - OLD DAYS.mp3",
      "Russ - Psycho (Pt. 2).mp3",
      "Russ - Ride Slow.mp3",
      "Russ - Seduce.mp3",
      "Russ - September 16.mp3",
      "Russ - Some Time.mp3",
      "Russ - SUMMER AT 7.mp3",
      "Russ - That Was Me.mp3",
      "Russ - The Flute Song.mp3",
      "Russ - Waves.mp3",
      "Russ - Yes Sir.mp3"
    ],
    artistID: 124,
  },
  {
    path: "silent-sanctuary",
    artistName: "Silent Sanctuary",
    musics: [
      "Silent Sanctuary - 14.mp3",
      "Silent Sanctuary - Abot Langit.mp3",
      "Silent Sanctuary - Bumalik Ka Na Sa'Kin.mp3",
      "Silent Sanctuary - Dahilan.mp3",
      "Silent Sanctuary - Di Na Kita Mahal.mp3",
      "Silent Sanctuary - Hiling.mp3",
      "Silent Sanctuary - Ikaw Lamang.mp3",
      "Silent Sanctuary - Kundiman.mp3",
      "Silent Sanctuary - Lambing.mp3",
      "Silent Sanctuary - Malayo Na Tayo.mp3",
      "Silent Sanctuary - Meron Nang Iba.mp3",
      "Silent Sanctuary - Paalam.mp3",
      "Silent Sanctuary - Pasensya Ka Na.mp3",
      "Silent Sanctuary - Rebound.mp3",
      "Silent Sanctuary - Sana Ngayong Pasko.mp3",
      "Silent Sanctuary - Sayo.mp3",
    ],
    artistID: 87,
  },
  {
    path: "slipknot",
    artistName: "Slipknot",
    musics: [
      "Slipknot - Before I Forget.mp3",
      "Slipknot - Dead Memories.mp3",
      "Slipknot - Psychosocial.mp3",
      "Slipknot - Spit It Out.mp3",
      "Slipknot - Wait And Bleed.mp3",
    ],
    artistID: 88,
  },
  {
    path: "snoop-dogg",
    artistName: "Snoop Dogg",
    musics: [
      "Snoop Dogg - Drop It Like Its Hot.mp3",
      "Snoop Dogg - SMOKE WEED EVERYDAY.mp3",
    ],
    artistID: 88,
  },
  {
    path: "system-of-a-down",
    artistName: "System Of A Down",
    musics: [
      "System Of A Down - Aerials.mp3",
      "System Of A Down - B.Y.O.B..mp3",
      "System Of A Down - Chop Suey!.mp3",
      "System Of A Down - Toxicity.mp3",
    ],
    artistID: 89,
  },
  {
    path: "taylor-swift",
    artistName: "Taylor Swift",
    musics: [
      "Taylor Swift - Back To December.mp3",
      "Taylor Swift - Bad Blood.mp3",
      "Taylor Swift - Blank Space.mp3",
      "Taylor Swift - Call It What You Want.mp3",
      "Taylor Swift - cardigan.mp3",
      "Taylor Swift - Gorgeous.mp3",
      "Taylor Swift - Look What You Made Me Do.mp3",
      "Taylor Swift - Love Story.mp3",
      "Taylor Swift - mirrorball.mp3",
      "Taylor Swift - Ours.mp3",
      "Taylor Swift - The Man.mp3",
      "Taylor Swift - The Way I Loved You.mp3",
      "Taylor Swift - You Belong With Me.mp3",
    ],
    artistID: 90,
  },
  {
    path: "the-1975",
    artistName: "The 1975",
    musics: [
      "The 1975 - Chocolate.mp3",
      "The 1975 - Girls.mp3",
      "The 1975 - Love Me.mp3",
      "The 1975 - Robbers.mp3",
      "The 1975 - Somebody Else.mp3",
      "The 1975 - The Sound.mp3",
    ],
    artistID: 91,
  },
  {
    path: "the-black-eyed-peas",
    artistName: "The Black Eyed Peas",
    musics: [
      "The Black Eyed Peas - I Gotta Feeling.mp3",
      "The Black Eyed Peas - My Humps.mp3",
      "The Black Eyed Peas - Shut Up.mp3",
      "The Black Eyed Peas - The APL Song.mp3",
      "The Black Eyed Peas - The Time.mp3",
      "The Black Eyed Peas - Where Is The Love.mp3",
    ],
    artistID: 92,
  },
  {
    path: "the-bootleg-boy",
    artistName: "The Bootleg Boy",
    musics: [
      "The Bootleg Boy - Addict. & Rewind - have you ever been in love_.mp3",
      "The Bootleg Boy - Chevy - I Know a Place.mp3",
      "The Bootleg Boy - Imfinenow & Joshua Mine - Be With You.mp3",
      "The Bootleg Boy - Julia Alexa - if u can take my pain away.mp3",
      "The Bootleg Boy - Kayou. & fawlin - I Tried.mp3",
      "The Bootleg Boy - lofi songs for childhood days.mp3",
      "The Bootleg Boy - lofi songs for rainy days.mp3",
      "The Bootleg Boy - lofi songs for warm days.mp3",
      "The Bootleg Boy - lofi songs for when you can't sleep.mp3",
      "The Bootleg Boy - lofi songs if you're having a bad week.mp3",
      "The Bootleg Boy - lofi songs if you're having a rough day.mp3",
      "The Bootleg Boy - Love hurts ~ sad lofi mix.mp3",
      "The Bootleg Boy - NÜ - i can't fight this (ft. Ivri).mp3",
      "The Bootleg Boy - RAINING IN ＮＡＧＡＳＡＫＩ (Lofi HipHop).mp3",
      "The Bootleg Boy - Rnla & zevia - Toxicity.mp3",
      "The Bootleg Boy - sad lofi for haunted souls.mp3",
      "The Bootleg Boy - Teqkoi - afraid of loving you.mp3",
      "The Bootleg Boy - Zaini - you felt like home.mp3",
    ],
    artistID: 93,
  },
  {
    path: "the-chainsmokers",
    artistName: "The Chainsmokers",
    musics: [
      "The Chainsmokers - All We Know.mp3",
      "The Chainsmokers - Closer.mp3",
      "The Chainsmokers - Don't Let Me Down.mp3",
      "The Chainsmokers - Hope.mp3",
      "The Chainsmokers - Inside Out.mp3",
      "The Chainsmokers - Paris.mp3",
      "The Chainsmokers - Roses.mp3",
      "The Chainsmokers - Something Just Like This.mp3",
    ],
    artistID: 94,
  },
  {
    path: "the-script",
    artistName: "The Script",
    musics: [
      "The Script - Breakeven.mp3",
      "The Script - Superheroes.mp3",
      "The Script - The Man Who Can’t Be Moved.mp3",
    ],
    artistID: 95,
  },
  {
    path: "the-walters",
    artistName: "The Walters",
    musics: [
      "The Walters - Autumn Leaves.mp3",
      "The Walters - Cottage Roads.mp3",
      "The Walters - Goodbye Baby.mp3",
      "The Walters - I Love You So.mp3",
      "The Walters - Life.mp3",
      "The Walters - Sweet Marie.mp3",
      "The Walters - What's Left.mp3",
    ],
    artistID: 96,
  },
  {
    path: "the-weeknd",
    artistName: "The Weeknd",
    musics: [
      "The Weeknd - A Tale By Quincy.mp3",
      "The Weeknd - Best Friends.mp3",
      "The Weeknd - Blinding Lights.mp3",
      "The Weeknd - Call Out My Name.mp3",
      "The Weeknd - Can't Feel My Face.mp3",
      "The Weeknd - Die For You.mp3",
      "The Weeknd - Don't Break My Heart.mp3",
      "The Weeknd - Every Angel Is Terrifying.mp3",
      "The Weeknd - Gasoline.mp3",
      "The Weeknd - Heartless.mp3",
      "The Weeknd - How Do I Make You Love Me.mp3",
      "The Weeknd - Is There Someone Else.mp3",
      "The Weeknd - Less Than Zero.mp3",
      "The Weeknd - Montreal.mp3",
      "The Weeknd - Out Of Time.mp3",
      "The Weeknd - Privilege.mp3",
      "The Weeknd - Save Your Tears.mp3",
      "The Weeknd - Starboy.mp3",
      "The Weeknd - Starry Eyes.mp3",
      "The Weeknd - Take My Breath.mp3",
      "The Weeknd - The Hills.mp3",
      "The Weeknd - The Morning.mp3",
      "The Weeknd - Too Late.mp3",
    ],
    artistID: 97,
  },
  {
    path: "trap-nation",
    artistName: "Trap Nation",
    musics: [
      "Trap Nation - 8 Graves - Begging To Bleed.mp3",
      "Trap Nation - OMIDO - LSD.mp3",
      "Trap Nation - Vanic - Save Yourself.mp3",
      "Trap Nation - Vanic x K.Flay - So Slow.mp3",
    ],
    artistID: 98,
  },
  {
    path: "troye-sivan",
    artistName: "Troye Sivan",
    musics: [
      "Troye Sivan - 1999.mp3",
      "Troye Sivan - Angel Baby.mp3",
      "Troye Sivan - could cry just thinkin about you.mp3",
      "Troye Sivan - Dance To This ft. Ariana Grande.mp3",
      "Troye Sivan - Easy.mp3",
      "Troye Sivan - FOOLS.mp3",
      "Troye Sivan - im so tired... ft. Lauv.mp3",
      "Troye Sivan - Strawberries and Cigarettes.mp3",
      "Troye Sivan - There For You ft. Martin Garrix.mp3",
      "Troye Sivan - WILD.mp3",
      "Troye Sivan - YOUTH.mp3",
    ],
    artistID: 98,
  },
  {
    path: "twenty-one-pilots",
    artistName: "Twenty One Pilots",
    musics: [
      "Twenty One Pilots - Cancer.mp3",
      "Twenty One Pilots - Chlorine.mp3",
      "Twenty One Pilots - Choker.mp3",
      "Twenty One Pilots - Level of Concern.mp3",
      "Twenty One Pilots - Morph.mp3",
      "Twenty One Pilots - My Blood.mp3",
      "Twenty One Pilots - Ride.mp3",
      "Twenty One Pilots - Shy Away.mp3",
      "Twenty One Pilots - Stressed Out.mp3",
      "Twenty One Pilots - The Hype.mp3",
    ],
    artistID: 99,
  },
  {
    path: "twice",
    artistName: "TWICE",
    musics: [
      "TWICE - BDZ.mp3",
      "TWICE - CHEER UP.mp3",
      "TWICE - CHILLAX.mp3",
      "TWICE - CRY FOR ME.mp3",
      "TWICE - Dance The Night Away.mp3",
      "TWICE - FANCY.mp3",
      "TWICE - Feel Special.mp3",
      "TWICE - Heart Shaker.mp3",
      "TWICE - HO!.mp3",
      "TWICE - I CAN'T STOP ME.mp3",
      "TWICE - KNOCK KNOCK.mp3",
      "TWICE - Kura Kura.mp3",
      "TWICE - LIKELY.mp3",
      "TWICE - LIKEY.mp3",
      "TWICE - MORE & MORE.mp3",
      "TWICE - Shot thru the heart.mp3",
      "TWICE - Strawberry Moon.mp3",
      "TWICE - STUCK.mp3",
      "TWICE - Touchdown.mp3",
      "TWICE - TT.mp3",
      "TWICE - What is Love.mp3",
      "TWICE - YES or YES.mp3",
      "TWICE - 다시 해줘 Do it again.mp3",
    ],
    artistID: 100,
  },
  {
    path: "unique-salonga",
    artistName: "Unique Salonga",
    musics: [
      "Unique Salonga - Bukod-Tangi.mp3",
      "Unique Salonga - Huwag Ka Sanang Magagalit.mp3",
      "Unique Salonga - Jules.mp3",
      "Unique Salonga - Lamang Lupa.mp3",
      "Unique Salonga - Mga Katulad Mo.mp3",
      "Unique Salonga - Midnight Sky.mp3",
      "Unique Salonga - Pahinga.mp3",
      "Unique Salonga - Sino.mp3",
    ],
    artistID: 910,
  },
  {
    path: "we-the-kings",
    artistName: "We The Kings",
    musics: [
      "We The Kings - Heaven Can Wait.mp3",
      "We The Kings - Sad Song (Slowed).mp3",
      "We The Kings - Sad Song.mp3",
      "We The Kings - We'll Be A Dream.mp3",
    ],
    artistID: 101,
  },
  {
    path: "wiz-khalifa",
    artistName: "Wiz Khalifa",
    musics: [
      "Wiz Khalifa - Black And Yellow.mp3",
      "Wiz Khalifa - Hopeless Romantic feat. Swae Lee.mp3",
      "Wiz Khalifa - In The Cut.mp3",
      "Wiz Khalifa - King Of Everything.mp3",
      "Wiz Khalifa - KK ft. Project Pat and Juicy J.mp3",
      "Wiz Khalifa - Let It Go feat. Akon.mp3",
      "Wiz Khalifa - Lit.mp3",
      "Wiz Khalifa - Medicated.mp3",
      "Wiz Khalifa - Mezmorized.mp3",
      "Wiz Khalifa - No Permission.mp3",
      "Wiz Khalifa - No Sleep.mp3",
      "Wiz Khalifa - Promises.mp3",
      "Wiz Khalifa - Roll Up.mp3",
      "Wiz Khalifa - Say So.mp3",
      "Wiz Khalifa - See You Again ft. Charlie Puth.mp3",
      "Wiz Khalifa - So High ft. Ghost Loft.mp3",
      "Wiz Khalifa - Something New.mp3",
      "Wiz Khalifa - True Colors.mp3",
      "Wiz Khalifa - We Dem Boyz.mp3",
      "Wiz Khalifa - Work Hard Play Hard.mp3",
      "Wiz Khalifa - Young, Wild & Free.mp3",
    ],
    artistID: 102,
  },
  {
    path: "yoasobi",
    artistName: "YOASOBI",
    musics: [
      "YOASOBI - 「ハルジオン・Halzion」.mp3",
      "YOASOBI - Haruka ハルカ.mp3",
      "YOASOBI - Probably.mp3",
      "YOASOBI - Racing into the Night.mp3",
      "YOASOBI - Tabun たぶん.mp3",
    ],
    artistID: 103,
  },
  {
    path: "zack-tabudlo",
    artistName: "Zack Tabudlo",
    musics: [
      "Zack Tabudlo - Binibini.mp3",
      "Zack Tabudlo - Habang Buhay.mp3",
      "Zack Tabudlo - Hindi Ko Kaya.mp3",
      "Zack Tabudlo - Iyong Iyo.mp3",
      "Zack Tabudlo - Nangangamba.mp3",
      "Zack Tabudlo - Sigurado.mp3",
      "Zack Tabudlo - Simula Palang Nung Una.mp3",
    ],
    artistID: 104,
  },
  {
    path: "zedd",
    artistName: "Zedd",
    musics: ["Zedd - Clarity.mp3", "Zedd - Stay.mp3", "Zedd - The Middle.mp3"],
    artistID: 105,
  },
  {
    path: "zelle",
    artistName: "Zelle",
    musics: ["Zelle - Sabihin.mp3"],
    artistID: 106,
  },
  {
    path: "zild",
    artistName: "Zild",
    musics: [
      "Zild - A Love Song.mp3",
      "Zild - dila.mp3",
      "Zild - Hele.mp3",
      "Zild - Huminga.mp3",
      "Zild - Ibang Planeta.mp3",
      "Zild - iiwanan ng lahat.mp3",
      "Zild - Kyusi.mp3",
      "Zild - Paalam Mahal.mp3",
      "Zild - sinungaling.mp3",
      "Zild - takbo ng panahon.mp3"
    ],
    artistID: 107
  }
];

export const albumCovers = {
  "gian": {
    "GIAN - Tayo.mp3": "Tayo.jpg",
  }
}

// Bundle all of musics from all of the music artists.

const allMusicsTemp = [];
let  i = 0;
for (i = 0; i < bodyData.length; i++) {
  allMusicsTemp.push(...bodyData[i].musics);
}

export const allMusics = allMusicsTemp;

export const playlists = [
  {
    playlistID: 0,
    playlistName: "Classic OPMs",
    musics: [
      "Ben&Ben - Araw-Araw.mp3",
      "Ben&Ben - Di Ka Sayang.mp3",
      "Ben&Ben - Nakikinig ka ba sa Akin.mp3",
      "Ben&Ben - Pagtingin.mp3",
      "Cueshe - 24 Hours.mp3",
      "Cueshe - Back To Me.mp3",
      "Cueshe - Borrowed Time.mp3",
      "Cueshe - Can't Let You Go.mp3",
      "Cueshe - Stay.mp3",
      "Cueshe - Ulan.mp3",
      "December Avenue - Bulong.mp3",
      "December Avenue - Eroplanong Papel.mp3",
      "December Avenue - Kahit 'Di Mo Alam.mp3",
      "December Avenue - Sa Ngalan Ng Pag-Ibig.mp3",
      "EMMAN - Teka Lang.mp3",
      "EMMAN - Uuwian.mp3",
      "Eraserheads - Alapaap.mp3",
      "Eraserheads - Ang Huling El Bimbo.mp3",
      "Eraserheads - Harana.mp3",
      "Eraserheads - Kailan.mp3",
      "Eraserheads - Ligaya.mp3",
      "Eraserheads - Maselang Bahaghari.mp3",
      "Eraserheads - Toyang.mp3",
      "Eraserheads - With A Smile.mp3",
      "Munimuni - Bawat Piyesa.mp3",
      "Munimuni - Sa'yo.mp3",
      "Parokya Ni Edgar - Alumni Homecoming.mp3",
      "Parokya Ni Edgar - Bagsakan.mp3",
      "Parokya Ni Edgar - Barkada.mp3",
      "Parokya Ni Edgar - Buloy.mp3",
      "Parokya Ni Edgar - Gitara.mp3",
      "Parokya Ni Edgar - Picha Pie.mp3",
      "Parokya Ni Edgar - Sampip.mp3",
      "Parokya Ni Edgar - Your Song.mp3",
      "Silent Sanctuary - 14.mp3",
      "Silent Sanctuary - Abot Langit.mp3",
      "Silent Sanctuary - Bumalik Ka Na Sa'Kin.mp3",
      "Silent Sanctuary - Hiling.mp3",
      "Silent Sanctuary - Ikaw Lamang.mp3",
      "Silent Sanctuary - Kundiman.mp3",
      "Silent Sanctuary - Pasensya Ka Na.mp3",
      "Silent Sanctuary - Rebound.mp3",
      "Silent Sanctuary - Sayo.mp3",
    ],
  },
  {
    playlistID: 1,
    playlistName: "Lofi",
    musics: [
      "ChilledCow - 1 A.M Study Session - (lofi hip hop chill beats).mp3",
      "ChilledCow - 2 A.M Study Session - (lofi hip hop chill beats).mp3",
      "ChilledCow - 4 A.M Study Session - (lofi hip hop chill beats).mp3",
      "ChilledCow - Brillion. - Bedtime Stories.mp3",
      "ChilledCow - Casiio - Wondering.mp3",
      "ChilledCow - DLJ - Night Emotions.mp3",
      "ChilledCow - Dontcry x Glimlip - 777.mp3",
      "ChilledCow - Fatb - Conscious Ego.mp3",
      "ChilledCow - Idealism - Last Time.mp3",
      "ChilledCow - Kupla - Kingdom In Blue.mp3",
      "ChilledCow - Kupla - Life Forms.mp3",
      "ChilledCow - Lazy Sunday - (lofi hip hop chill beats).mp3",
      "ChilledCow - Mell-ø x Ambulo - Afloat Again.mp3",
      "ChilledCow - Monma - Calm Lands.mp3",
      "ChilledCow - Refeeld x Project AER - Chance Encounter.mp3",
      "ChilledCow - Tysu x Spencer Hunt - Window Seat.mp3",
      "Dreamy - Because music cures every problem ~ lofi hip hop mix.mp3",
      "Dreamy - Believe in the dream ~ lofi hip hop mix.mp3",
      "Dreamy - Breathing dreams like air ~ lofi hip hop mix.mp3",
      "Dreamy - Guitar Vibe ~ lofi hip hop mix.mp3",
      "Dreamy - It's 2am. I need you here ~ lofi hip hop mix.mp3",
      "Dreamy - Let's just stay here forever ~ lofi hip hop mix.mp3",
      "Dreamy - Lullaby to the Stars ~ lofi hip hop mix - study beats.mp3",
      "Dreamy - Raining day ~ lofi hip hop mix.mp3",
      "Dreamy - Solitude ~ lofi hip hop mix.mp3",
      "Dreamy - Stay with me ~ lofi hip hop mix.mp3",
      "Dreamy - Your smile — My everything ~ lofi hip hop mix.mp3",
      "Dreamy - Yūgen ~ Japanese Lofi Hip-Hop.mp3",
      "The Bootleg Boy - Chevy - I Know a Place.mp3",
      "The Bootleg Boy - Imfinenow & Joshua Mine - Be With You.mp3",
      "The Bootleg Boy - Julia Alexa - if u can take my pain away.mp3",
      "The Bootleg Boy - Kayou. & fawlin - I Tried.mp3",
      "The Bootleg Boy - lofi songs for childhood days.mp3",
      "The Bootleg Boy - lofi songs for rainy days.mp3",
      "The Bootleg Boy - lofi songs for warm days.mp3",
      "The Bootleg Boy - lofi songs for when you can't sleep.mp3",
      "The Bootleg Boy - lofi songs if you're having a bad week.mp3",
      "The Bootleg Boy - lofi songs if you're having a rough day.mp3",
      "The Bootleg Boy - Love hurts ~ sad lofi mix.mp3",
      "The Bootleg Boy - NÜ - i can't fight this (ft. Ivri).mp3",
      "The Bootleg Boy - Rnla & zevia - Toxicity.mp3",
      "The Bootleg Boy - Teqkoi - afraid of loving you.mp3",
      "The Bootleg Boy - Zaini - you felt like home.mp3",
    ],
  },
  {
    playlistID: 2,
    playlistName: "Japanese Songs ❤",
    musics: [
      "藤井 風 (Fujii Kaze) - もうええわ (Mo-Eh-Wa).mp3",
      "藤井 風 (Fujii Kaze) - 優しさ (YASASHISA).mp3",
      "藤井 風 (Fujii Kaze) - 帰ろう (Kaerou).mp3",
      "藤井 風 (Fujii Kaze) - 旅路 (Tabiji).mp3",
      "RADWIMPS - Nandemonaiya.mp3",
      "RADWIMPS - Sparkle.mp3",
      "YOASOBI - 「ハルジオン・Halzion」.mp3",
      "YOASOBI - Haruka ハルカ.mp3",
      "YOASOBI - Probably.mp3",
      "YOASOBI - Racing into the Night.mp3",
      "YOASOBI - Tabun たぶん.mp3",
    ],
  },
];

// export const playlists = [
//   {
//     path: "70s 80s 90s",
//     playlistName: "70s 80s 90s",
//     musics: [
//       "4 Non Blondes - What's Up.mp3",
//       "AC_DC - Back In Black.mp3",
//       "AC_DC - Thunderstruck.mp3",
//       "Aerosmith - Crazy.mp3",
//       "Aerosmith - I Don't Want to Miss a Thing.mp3",
//       "All-4-One - I Swear.mp3",
//       "Backstreet Boys - As Long As You Love Me.mp3",
//       "Backstreet Boys - Everybody.mp3",
//       "Backstreet Boys - I Want It That Way.mp3",
//       "Bon Jovi - Always.mp3",
//       "Britney Spears - ...Baby One More Time.mp3",
//       "Bryan Adams - (Everything I Do) I Do It For You.mp3",
//       "Bryan Adams - Please Forgive Me.mp3",
//       "Bryan Adams - Summer Of '69.mp3",
//       "Celene Dion - My Heart Will Go On.mp3",
//       "Elton John - Circle Of Life.mp3",
//       "Eric Carmen - All by Myself.mp3",
//       "Eric Clapton - Tears In Heaven.mp3",
//       "Eric Clapton - Wonderful Tonight.mp3",
//       "Extreme - More Than Words.mp3",
//       "Fugees - Killing Me Softly With His Song.mp3",
//       "Gotye - Somebody That I Used To Know (feat. Kimbra).mp3",
//       "Guns N' Roses - November Rain.mp3",
//       "Heart - Alone.mp3",
//       "Mariah Carey - All I Want For Christmas Is You.mp3",
//       "Mariah Carey - Hero.mp3",
//       "Mariah Carey - Without You.mp3",
//       "Metallica_ Nothing Else Matters.mp3",
//       "Michael Bublé - Always On My Mind.mp3",
//       "Michael Bublé - Everything.mp3",
//       "Michael Bublé - Feeling Good.mp3",
//       "Michael Bublé - Haven't Met You Yet.mp3",
//       "Michael Bublé - Home.mp3",
//       "Michael Bublé - It's A Beautiful Day.mp3",
//       "Michael Jackson - They Don’t Care About Us.mp3",
//       "Modern Talking - Cheri Cheri Lady.mp3",
//       "Modern Talking - You're My Heart, You're My Soul.mp3",
//       "Nirvana - Smells Like Teen Spirit.mp3",
//       "No Doubt - Don't Speak.mp3",
//       "Oasis - Wonderwall.mp3",
//       "Queen - Another One Bites the Dust.mp3",
//       "Queen - Crazy Little Thing Called Love.mp3",
//       "Queen - We Are The Champions .mp3",
//       "Queen - We Will Rock You.mp3",
//       "R. Kelly - I Believe I Can Fly.mp3",
//       "R.E.M. - Losing My Religion.mp3",
//       "Rick Astley - Never Gonna Give You Up.mp3",
//       "Rick Astley - Together Forever.mp3",
//       "Ricky Martin - Livin' La Vida Loca.mp3",
//       "Roxette - It Must Have Been Love.mp3",
//       "Savage Garden - Truly Madly Deeply.mp3",
//       "Scorpions - Wind Of Change.mp3",
//       "Smash Mouth - All Star.mp3",
//       "Soul Asylum - Runaway Train.mp3",
//       "Spice Girls - Wannabe.mp3",
//       "The Cranberries - Zombie.mp3",
//       "The Police - Every Breath You Take.mp3",
//       "The Verve - Bitter Sweet Symphony.mp3",
//       "Toni Braxton - Un-Break My Heart.mp3",
//       "UB40 - (I Can't Help) Falling In Love With You.mp3",
//       "Vanilla Ice - Ice Ice Baby.mp3",
//       "Whitney Houston - I Have Nothing.mp3",
//       "Whitney Houston - I Will Always Love You.mp3",
//     ],
//     playlistID: 1,
//   },
//   {
//     path: "G(old)",
//     playlistName: "G(old)",
//     musics: [
//       "Abba - Chiquitita.mp3",
//       "Air Supply - Chances.mp3",
//       "Air Supply - Having You Near Me.mp3",
//       "Air Supply - I Can Wait Forever.mp3",
//       "Air Supply - I Can't Let Go.mp3",
//       "Air Supply - I'll Never Get Enough of You.mp3",
//       "Air Supply - Lonely Is The Night.mp3",
//       "Air Supply - Making Love Out of Nothing at All.mp3",
//       "Air Supply - Sweet Dreams.mp3",
//       "Barbara Dickson - Caravan.mp3",
//       "Barbra Streisand - Woman In Love.mp3",
//       "Bon Jovi - Never Say Goodbye.mp3",
//       "Bonnie Tyler - If I Sing You a Love Song.mp3",
//       "Cher - After All.mp3",
//       "Chicago - Hard To Say I'm Sorry.mp3",
//       "Chris Walker - How Do You Heal A Broken Heart.mp3",
//       "Dan Hill - Why Do We Always Hurt The Ones We Love.mp3",
//       "David Gates - Take Me Now.mp3",
//       "Dennis DeYoung - Desert Moon.mp3",
//       "Eagles - The Last Resort.mp3",
//       "Eric Clapton - Wonderful Tonight.mp3",
//       "Europe - Carrie.mp3",
//       "Helen Reddy - I Can't Say Goodbye To You.mp3",
//       "Jimmy Harnen with Synch - Where Are You Now.mp3",
//       "Kenny Rogers - She Believes In Me.mp3",
//       "Kenny Rogers & Anne Murray - If I Ever Fall in Love Again.mp3",
//       "Lionel Richie - Stuck On You (Lyrics).mp3",
//       "Lobo - How Can I Tell Her.mp3",
//       "Maureen McGovern - We Could Have It All.mp3",
//       "Melissa Manchester - If This Is Love.mp3",
//       "Midnight Blue - ELO (lyrics).mp3",
//       "Mike Reno - Almost Paradise.mp3",
//       "Moira & Jason - Ikaw At Ako (Lyric Video).mp3",
//       "Nazareth - Love Hurts.mp3",
//       "Nazareth - Where Are You Now.mp3",
//       "Sheryn Regis - Sinungaling Mong Puso (Official Lyric Video).mp3",
//       "Tommy Shaw - Count On You.mp3",
//     ],
//     playlistID: 2,
//   },
//   {
//     path: "Nostalgia",
//     playlistName: "Nostalgia",
//     musics: [
//       "3 Doors Down - Here Without You.mp3",
//       "Akon - Don't Matter.mp3",
//       "Akon - Right Now.mp3",
//       "Akon - Sorry, Blame It On Me.mp3",
//       "Alicia Keys - No One.mp3",
//       "Austin Mahone - All I Ever Need.mp3",
//       "Avril Lavigne - Breakaway.mp3",
//       "Avril Lavigne - Complicated.mp3",
//       "Avril Lavigne - Head Above Water.m4a",
//       "Avril Lavigne - Here's To Never Growing Up.mp3",
//       "Avril Lavigne - My Happy Ending.mp3",
//       "Avril Lavigne - When You're Gone.mp3",
//       "Avril Lavigne - Wish You Were Here.mp3",
//       "B.o.B - Airplanes.mp3",
//       "Bastille - Pompeii.mp3",
//       "Beyoncé - Halo.mp3",
//       "Beyoncé - If I Were A Boy.mp3",
//       "Beyoncé - Irreplaceable.mp3",
//       "Blink-182 - Adam's Song.mp3",
//       "Blink-182 - All The Small Things.mp3",
//       "Blink-182 - First Date.mp3",
//       "Blink-182 - I Miss You.mp3",
//       "Blink-182 - Stay Together For The Kids.mp3",
//       "Blink-182 - What's My Age Again.mp3",
//       "Bon Jovi - Bed Of Roses.mp3",
//       "Bon Jovi - It's My Life.mp3",
//       "Britney Spears - Toxic.mp3",
//       "Bruno Mars - It Will Rain.mp3",
//       "Bruno Mars - Locked Out Of Heaven.mp3",
//       "Calvin Harris - Summer.mp3",
//       "Carpenters - I Won't Last A Day Without You (Lyrics).mp3",
//       "Chris Brown - With You.mp3",
//       "Coldplay - Clocks.mp3",
//       "Coldplay - Fix You.mp3",
//       "Coldplay - O.mp3",
//       "Coldplay - Paradise.mp3",
//       "Coldplay - Yellow.mp3",
//       "Creed - One Last Breath.mp3",
//       "Daughtry - Over You.mp3",
//       "Disturbed - Down With The Sickness.mp3",
//       "Eminem - The Monster.mp3",
//       "Eminem - The Real Slim Shady.mp3",
//       "Enrique Iglesias - Hero.mp3",
//       "Evanescence - Bring Me To Life.mp3",
//       "Evanescence - My Immortal.mp3",
//       "Fergie - Big Girls Don't Cry.mp3",
//       "Five for Fighting - Superman (It's Not Easy).mp3",
//       "Flo Rida - Right Round.mp3",
//       "Foster The People - Pumped up Kicks.mp3",
//       "Hinder - Lips Of An Angel.mp3",
//       "Hoobastank - The Reason.mp3",
//       "Iggy Azalea - Fancy.mp3",
//       "Jason Derulo - It Girl.mp3",
//       "Jason Derulo - Whatcha Say.mp3",
//       "Jason Mraz - I'm Yours.mp3",
//       "Jay-Z - Empire State Of Mind.mp3",
//       "John Legend - All of Me.mp3",
//       "Katy Perry - Hot N Cold.mp3",
//       "Kelly Clarkson - Because Of You.mp3",
//       "Lady Gaga - Bad Romance.mp3",
//       "Leona Lewis - Bleeding Love.mp3",
//       "Lifehouse - You And Me.mp3",
//       "MAGIC! - Rude.mp3",
//       "Martin Garrix & Dua Lipa - Scared To Be Lonely.mp3",
//       "Matchbox Twenty - Unwell.mp3",
//       "Miki Matsubara - Stay With Me.mp3",
//       "Miley Cyrus - Party In The U.S.A..mp3",
//       "My Chemical Romance - Famous Last Words.mp3",
//       "My Chemical Romance - Helena.mp3",
//       "My Chemical Romance - I Don't Love You.mp3",
//       "My Chemical Romance - Teenagers.mp3",
//       "My Chemical Romance - Welcome To The Black Parade.mp3",
//       "Ne-Yo - So Sick.mp3",
//       "Oasis - Wonderwall.mp3",
//       "OMI - Cheerleader.mp3",
//       "OneRepublic - Counting Stars.mp3",
//       "OneRepublic - Good Life.mp3",
//       "OneRepublic - If I Lose Myself.mp3",
//       "Paramore - Ain't It Fun.mp3",
//       "Paramore - Brick By Boring Brick.mp3",
//       "Paramore - CrushCrushCrush.mp3",
//       "Paramore - Decode.mp3",
//       "Paramore - Hard Times.mp3",
//       "Paramore - Ignorance.mp3",
//       "Paramore - Last Hope.mp3",
//       "Paramore - Monster.mp3",
//       "Paramore - My Heart.mp3",
//       "Paramore - Still Into You.mp3",
//       "Paramore - That's What You Get.mp3",
//       "Paramore - The Only Exception.mp3",
//       "Paramore - Turn It Off.mp3",
//       "Paramore - When It Rains.mp3",
//       "Pitbull - Timber.mp3",
//       "R.E.M. - Losing My Religion.mp3",
//       "Rihanna - Don't Stop The Music.mp3",
//       "Rihanna - Take A Bow.mp3",
//       "Rihanna - Umbrella.mp3",
//       "Sean Kingston - Beautiful Girls.mp3",
//       "Shaggy - Angel.mp3",
//       "Simple Plan - Welcome To My Life.mp3",
//       "Skylar Grey - I'm Coming Home.mp3",
//       "Slipknot - Duality.mp3",
//       "Snow Patrol - Chasing Cars.mp3",
//       "Soulja Boy - Crank That.mp3",
//       "System Of A Down - Aerials.mp3",
//       "System Of A Down - B.Y.O.B..mp3",
//       "System Of A Down - Chop Suey!.mp3",
//       "System Of A Down - Toxicity.mp3",
//       "T-Pain - 5 O'Clock.mp3",
//       "Taylor Swift - Back To December.mp3",
//       "Taylor Swift - Bad Blood.mp3",
//       "Taylor Swift - Blank Space.mp3",
//       "Taylor Swift - Call It What You Want.mp3",
//       "Taylor Swift - Cardigan.mp3",
//       "Taylor Swift - Gorgeous.mp3",
//       "Taylor Swift - Look What You Made Me Do.mp3",
//       "Taylor Swift - Love Story.mp3",
//       "Taylor Swift - Mirrorball.mp3",
//       "Taylor Swift - Ours.mp3",
//       "Taylor Swift - The Man.mp3",
//       "Taylor Swift - The Way I Loved You.mp3",
//       "Taylor Swift - You Belong With Me.mp3",
//       "The Black Eyed Peas - I Gotta Feeling.mp3",
//       "The Black Eyed Peas - Where Is The Love.mp3",
//       "The Calling - Wherever You Will Go.mp3",
//       "The Fray - How to Save a Life.mp3",
//       "The Police - Message In A Bottle.mp3",
//       "Timbaland - Apologize.mp3",
//       "Train - Hey, Soul Sister.mp3",
//       "Trevor Wesley - Chivalry Is Dead.mp3",
//       "Vanessa Carlton - A Thousand Miles.mp3",
//     ],
//     playlistID: 3,
//   },
// ];

// Archived songs & artists
// {
// 	"path": "bass-nation",
// 	"artistName": "Bass Nation",
// 	"musics": [
// 		"Bass Nation - AENEΛS - DIAMOND.mp3",
// 		"Bass Nation - alasen - temple.mp3",
// 		"Bass Nation - ALBUM VOL.1 - .50 CAL.mp3",
// 		"Bass Nation - ANTHEM II - Lukrative.mp3",
// 		"Bass Nation - Antikvng - Blue Moon.mp3",
// 		"Bass Nation - APASHE - Lord & Master.mp3",
// 		"Bass Nation - AVXP X COSMIC X THÉOS - SPACEMAN.mp3",
// 		"Bass Nation - Axel Thesleff - Bad Karma.mp3",
// 		"Bass Nation - Bailo Beatz - No Cap.mp3",
// 		"Bass Nation - Bass & Beard - Dimensions.mp3",
// 		"Bass Nation - BEATSMASH - Árēs.mp3",
// 		"Bass Nation - BLVCK - THE RING.mp3",
// 		"Bass Nation - bsterthegawd - grow.mp3",
// 		"Bass Nation - bsterthegawd - suffer.mp3",
// 		"Bass Nation - Calli Boom - Axiom.mp3",
// 		"Bass Nation - Calli Boom - Pulse.mp3",
// 		"Bass Nation - CALLI BOOM & SMOKA - MINDBLOW.mp3",
// 		"Bass Nation - Cardi B - Bodak Yellow (Y2k Remix).mp3",
// 		"Bass Nation - caustyk - VISCERAL.mp3",
// 		"Bass Nation - Chase Atlantic - Swim.mp3",
// 		"Bass Nation - DELAY - Before The Storm.mp3",
// 		"Bass Nation - DELP X DIEOM X COSTE X YABØII - ELITE.mp3",
// 		"Bass Nation - Dieom - sadistic.mp3",
// 		"Bass Nation - E.Y. BEATS X THÉOS - MOON.mp3",
// 		"Bass Nation - Fall 2020 Mix.mp3",
// 		"Bass Nation - Halloween Music Mix.mp3",
// 		"Bass Nation - HANZO - GREEN FIELDS II.mp3",
// 		"Bass Nation - hélix - ATHENA.mp3",
// 		"Bass Nation - HOPEX - Conquer.mp3",
// 		"Bass Nation - IGAZI - Changes.mp3",
// 		"Bass Nation - JACARO - Last Bastion.mp3",
// 		"Bass Nation - JAEGER - Don't Play.mp3",
// 		"Bass Nation - JAEGER - Kingpin.mp3",
// 		"Bass Nation - JAEGER - Sins.mp3",
// 		"Bass Nation - jai - DAMNATION.mp3",
// 		"Bass Nation - jai. - Apoll.mp3",
// 		"Bass Nation - Jordan Comolli - Paranormal 2.0.mp3",
// 		"Bass Nation - Jordan Comolli & Hilton - Absence.mp3",
// 		"Bass Nation - KAAD!K - ʀ ᴇ ʙ ᴏ ᴜ ɴ ᴅ.mp3",
// 		"Bass Nation - KÉDALOS - final fantasy.mp3",
// 		"Bass Nation - kellbender - ima boss.mp3",
// 		"Bass Nation - LBLVNC - AMADEUS.mp3",
// 		"Bass Nation - LBLVNC & BULWRD - Da Vinci.mp3",
// 		"Bass Nation - ledim - Ningen.mp3",
// 		"Bass Nation - LENNY - AVALON.mp3",
// 		"Bass Nation - LENNY & MCTR - HORUS.mp3",
// 		"Bass Nation - LOUD - Feels.mp3",
// 		"Bass Nation - LOUD - Thoughts.mp3",
// 		"Bass Nation - lucaf. - Exodus.mp3",
// 		"Bass Nation - MAKZO X ROSHIMA - FLASHBACK!.mp3",
// 		"Bass Nation - MCTR - Fearless.mp3",
// 		"Bass Nation - MCTR - WARZONE.mp3",
// 		"Bass Nation - MCTR - What U Say.mp3",
// 		"Bass Nation - MISOGI -  PINK2.mp3",
// 		"Bass Nation - Mr. Carmack - Unfocused.mp3",
// 		"Bass Nation - MYSTIC - UP!.mp3",
// 		"Bass Nation - New Year's Mix.mp3",
// 		"Bass Nation - NOAX - DEATH CHILL.mp3",
// 		"Bass Nation - noax - The End.mp3",
// 		"Bass Nation - NØCTRIS - COLOSSEUM.mp3",
// 		"Bass Nation - NOIXES - ATTENTION.mp3",
// 		"Bass Nation - NOIXES - Away.mp3",
// 		"Bass Nation - oshi - pink.mp3",
// 		"Bass Nation - OSIAS - BASS GOD.mp3",
// 		"Bass Nation - OSIAS - FURY.mp3",
// 		"Bass Nation - Osias - KING KALI.mp3",
// 		"Bass Nation - Quarantine Mix.mp3",
// 		"Bass Nation - qvtvna - Reika.mp3",
// 		"Bass Nation - REALM x E.Y. - Regicide.mp3",
// 		"Bass Nation - SACE - RISE.mp3",
// 		"Bass Nation - SKYPIERR - ULTRA INSTINCT.mp3",
// 		"Bass Nation - SL!DE X THROVN - REVELATION.mp3",
// 		"Bass Nation - stedry x that boi retrol - final boss 3.mp3",
// 		"Bass Nation - STXRM - THE TRAIL.mp3",
// 		"Bass Nation - Take Five - Say My Name.mp3",
// 		"Bass Nation - théos - falling down.mp3",
// 		"Bass Nation - THROVN - Behind My Back.mp3",
// 		"Bass Nation - vowl. - toxic.mp3",
// 		"Bass Nation - VRCTIC - METALICE.mp3",
// 		"Bass Nation - Willix - Apparat.mp3",
// 		"Bass Nation - Wizard - Hopin.mp3",
// 		"Bass Nation - YABØII & COSTE - LEGION.mp3",
// 		"Bass Nation - Zethis & EQZLN - Vengeance.mp3",
// 	],
// 	"artistID": 4
// },

// {
// 	"path": "dubstepgutter",
// 	"artistName": "DubstepGutter",
// 	"musics": [
// 		"Dubstepgutter - 6ix9ine - GOOBA.mp3",
// 		"Dubstepgutter - DubstepGutter - 10 Years of Anniversary Mix.mp3",
// 		"Dubstepgutter - Amidst - Voices.mp3",
// 		"Dubstepgutter - Azazal & Said - I Said Meow.mp3",
// 		"Dubstepgutter - Becko - Dead-End.mp3",
// 		"Dubstepgutter - BitWare - Insert Coin.mp3",
// 		"Dubstepgutter - D-Nasty - Control Me.mp3",
// 		"Dubstepgutter - ENT!TY - My Heart.mp3",
// 		"Dubstepgutter - Frequensphere - Heaven.mp3",
// 		"Dubstepgutter - Geoxor - Virtual.mp3",
// 		"Dubstepgutter - God's Warrior - Big Power.mp3",
// 		"Dubstepgutter - God's Warrior - Journey.mp3",
// 		"Dubstepgutter - GUTTER - Nostalgia.mp3",
// 		"Dubstepgutter - Kai Wachi - Photograph.mp3",
// 		"Dubstepgutter - KDrew - Sometimes.mp3",
// 		"Dubstepgutter - Marauda - Blunder.mp3",
// 		"Dubstepgutter - Millennial Trash - Anxiety.mp3",
// 		"Dubstepgutter - Phao - 2 Phut Hon.mp3",
// 		"Dubstepgutter - PUNYASO - Konoha's Kid.mp3",
// 		"Dubstepgutter - San Holo - Lift Me From The Ground.mp3",
// 		"Dubstepgutter - Seven Lions - Only Now.mp3",
// 		"Dubstepgutter - Sikdope - Follow.mp3",
// 		"Dubstepgutter - Skrillex - Make It Bun Dem.mp3",
// 		"Dubstepgutter - Snavs - Neo.mp3",
// 		"Dubstepgutter - Spag Heddy - It's Me.mp3",
// 		"Dubstepgutter - Spag Heddy - Permanent.mp3",
// 		"Dubstepgutter - Spag Heddy - Raise Ur Hands.mp3",
// 		"Dubstepgutter - Storyboard - Nightmare Lullaby.mp3",
// 		"Dubstepgutter - SVDDEN DEATH & Snails - DEATHMATCH.mp3",
// 		"Dubstepgutter - Syn - Synners.mp3",
// 		"Dubstepgutter - Teminite - Rise And Shine.mp3",
// 		"Dubstepgutter - Teminite & Panda Eyes - Highscore.mp3",
// 		"Dubstepgutter - vKompany - Feel It All.mp3",
// 		"Dubstepgutter - Vorso - Voltage.mp3",
// 		"Dubstepgutter - Wuki & Smokepurpp - Birdz.mp3"
// 	],
// 	"artistID": 18
// },

// {
// 	"path": "nocopyrightsounds",
// 	"artistName": "NoCopyrightSounds",
// 	"musics": [
// 		"NoCopyRightSounds - Abandoned - Out Of The Grave.mp3",
// 		"NoCopyRightSounds - Au5 & Last Heroes - Lush.m4a",
// 		"NoCopyRightSounds - Barren Gates & M.I.M.E - Enslaved.mp3",
// 		"NoCopyRightSounds - BEAUZ & JVNA - Crazy.mp3",
// 		"NoCopyRightSounds - Cartoon - C U Again.mp3",
// 		"NoCopyRightSounds - Culture Code - Make Me Move.mp3",
// 		"NoCopyRightSounds - Deflo & Lliam Taylor - Reflections.mp3",
// 		"NoCopyRightSounds - Diamond Eyes - Flutter.mp3",
// 		"NoCopyRightSounds - Diamond Eyes - Gravity.mp3",
// 		"NoCopyRightSounds - Diamond Eyes - Hold On.mp3",
// 		"NoCopyRightSounds - Dread Pitt - Reckless.mp3",
// 		"NoCopyRightSounds - Ellis - Clear My Head.mp3",
// 		"NoCopyRightSounds - ÉWN - The LighT.mp3",
// 		"NoCopyRightSounds - Glude - Dreamers.mp3",
// 		"NoCopyRightSounds - HYLO - Paradise.mp3",
// 		"NoCopyRightSounds - Jim Yosef - Let You Go.mp3",
// 		"NoCopyRightSounds - Jonny Koch & Annie Sollange - LOVE ME.mp3",
// 		"NoCopyRightSounds - Julius Dreisig & Zeus X Crona - Invisible.mp3",
// 		"NoCopyRightSounds - Kaivon - First Love.mp3",
// 		"NoCopyRightSounds - Koven - Never Have I Felt This.mp3",
// 		"NoCopyRightSounds - Kozah - Haha.mp3",
// 		"NoCopyRightSounds - Kozah - Heavens.mp3",
// 		"NoCopyRightSounds - Kozah - Paradox.mp3",
// 		"NoCopyRightSounds - Last Heroes x TwoWorldsApart - Eclipse.m4a",
// 		"NoCopyRightSounds - Lost Sky - Dreams.mp3",
// 		"NoCopyRightSounds - Lost Sky - Fearless pt.II.mp3",
// 		"NoCopyRightSounds - Lost Sky - Lost.mp3",
// 		"NoCopyRightSounds - Lost Sky - Where We Started.mp3",
// 		"NoCopyRightSounds - MAGNUS x Unread - Cool.mp3",
// 		"NoCopyRightSounds - Mike Vallas, Jagsy & quaggin. - Left My Heart In Pain.mp3",
// 		"NoCopyRightSounds - Mountkid - Dino.mp3",
// 		"NoCopyRightSounds - Mountkid - No Lullaby.mp3",
// 		"NoCopyRightSounds - NIVIRO - Demons.mp3",
// 		"NoCopyRightSounds - Paul_Flint - Watch The World Burn.m4a",
// 		"NoCopyRightSounds - Prismo - Stronger.mp3",
// 		"NoCopyRightSounds - ROY KNOX & Shiah Maisel - Living With Regret.mp3",
// 		"NoCopyRightSounds - Sinner's Heist - Streetlight People.mp3",
// 		"NoCopyRightSounds - Sub Urban - Cradles.mp3",
// 		"NoCopyRightSounds - Syn Cole - Keep Going.mp3",
// 		"NoCopyRightSounds - T-Mass - Ignoring My Heart.mp3",
// 		"NoCopyRightSounds - Unknown Brain - Inspiration.mp3",
// 		"NoCopyRightSounds - Unknown Brain - MATAFAKA.mp3",
// 		"NoCopyRightSounds - Unknown Brain - Perfect 10.mp3",
// 		"NoCopyRightSounds - Unknown Brain - Roots.mp3",
// 		"NoCopyRightSounds - Unknown Brain - Waiting.mp3",
// 		"NoCopyRightSounds - Unknown Brain - Why Do I.mp3",
// 		"NoCopyRightSounds - Unknown Brain & Anna Yvette - Twisted Reality.mp3",
// 		"NoCopyRightSounds - Unknown Brain x Rival - Control.mp3",
// 		"NoCopyRightSounds - Vanze - Forever.mp3",
// 		"NoCopyRightSounds - WiDE AWAKE - Something More.mp3"
// 	],
// 	"artistID": 42
// },
